### PR TITLE
Update README.md

### LINKED ISSUE #5: Mention the platform for the code in README.md
It would be great if someone could add the OS and IDE on which the code was written.
I've written the code in VS Code running on Windows 10 using a g++compiler version 9.2.0

### PR DESCRIPTION
**Pull request by pedrohcavalcante**
Changes for #5

### CODE REVIEW

**Review by VenkatVuddagiri — APPROVED** [review]
Could you also mention the youtube channel from which I've learnt.
It is Simple Snippets.
If possible add a link to the playlist

**Comment by VenkatVuddagiri** [comment]
The link to the playlist is below, please add that too
[Simple Snippets](https://www.youtube.com/playlist?list=PLIY8eNdw5tW_zX3OCzX7NJ8bL1p6pWfgG)

**Comment by VenkatVuddagiri** [comment]
I've approved your pull request, so it will start counting towards hactoberfest. Please complete the remaining things too.

**Comment by pedrohcavalcante** [comment]
@VenkatVuddagiri done

**Review by VenkatVuddagiri — APPROVED** [review]

**Comment by VenkatVuddagiri** [comment]
Thanks a lot for your contribution @pedrohcavalcante . It means a lot : )

**Pull request merged**
